import { defineConfig } from 'vite';
import monkey from 'vite-plugin-monkey';

export default defineConfig({
  plugins: [
    monkey({
      entry: 'src/main.js',
      userscript: {
          name: 'JHS-enhance',
          namespace: 'JHS-enhance',
        version: '3.3.7',
        author: 'xie bro,fireinrain',
        description: 'Jav-鉴黄师 增强脚本。列表页：作品状态标签、一键筛选、新作品检测、演员黑名单过滤；详情页：磁力链接高亮、DMM 多画质预览视频、标题翻译、整合字幕搜索（迅雷+SubTitleCat）并支持 115 直传、多源预览图（javfree/projectjav/javstore）含来源切换；数据：115 网盘目录匹配与多目录选择、云盘备份/恢复、跨 Tab 同步；其他：自动翻页、分类折叠、Top250、以图识图、热门榜单、评论查看、相关清单。支持 JavDB / JavBus / JavSee / SeeJav / FC2 / JavTrailers',
        license: 'MIT',
        icon: 'https://www.google.com/s2/favicons?sz=64&domain=javdb.com',
        match: [
          'https://javdb.com/*',
          'https://www.javbus.com/*',
        ],
        include: [
          'https://javdb*.com/*',
          'https://*javbus*/*',
          'https://*javsee*/*',
          'https://*seejav*/*',
          'https://javtrailers.com/*',
          'https://subtitlecat.com/*',
          'https://www.aliyundrive.com/*',
          'https://www.alipan.com/*',
          'https://115.com/*',
        ],
        exclude: [
          'https://*javbus*/forum/*',
          'https://*javbus*/*actresses',
          'https://*javsee*/forum/*',
          'https://*javsee*/*actresses',
          'https://*seejav*/forum/*',
          'https://*seejav*/*actresses',
        ],
        require: [
          'https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js',
          'https://cdn.jsdelivr.net/npm/tabulator-tables@6.5.2/dist/js/tabulator.min.js',
          'https://cdn.jsdelivr.net/npm/layui-layer@1.0.9/dist/layer.min.js',
          'https://cdn.jsdelivr.net/npm/blueimp-md5@2.19.0/js/md5.min.js',
          'https://cdn.jsdelivr.net/npm/toastify-js@1.12.0/src/toastify.min.js',
          'https://cdn.jsdelivr.net/npm/localforage@1.10.0/dist/localforage.min.js',
          'https://cdn.jsdelivr.net/npm/viewerjs@1.11.1/dist/viewer.min.js',
          'https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js',
        ],
        connect: [
          'xunlei.com',
          'geilijiasu.com',
          'aliyundrive.com',
          'aliyundrive.net',
          'ja.wikipedia.org',
          'beta.magnet.pics',
          'jdforrepam.com',
          'cc3001.dmm.co.jp',
          'cc3001.dmm.com',
          'www.dmm.co.jp',
          'www.dmm.com',
          'api.dmm.com',
          'special.dmm.co.jp',
          'adult.contents.fc2.com',
          'fc2ppvdb.com',
          '123av.com',
          'u3c3.com',
          'u9a9.com',
          'btsow.lol',
          'sukebei.nyaa.si',
          'javstore.net',
          'javbest.net',
          'missav.live',
          'jable.tv',
          'www.av.gl',
          'jav.rs',
          'javtrailers.com',
          'javdb.com',
          'javbus.com',
          'supjav.com',
          '115.com',
          'jianguoyun.com',
          '127.0.0.1',
          '*',
        ],
        grant: [
          'GM_xmlhttpRequest',
          'GM_openInTab',
          'unsafeWindow',
        ],
        'run-at': 'document-idle',
      },
      build: {
        fileName: 'jhs-enhance.user.js',
        externalGlobals: {
          'jquery': '$',
          'localforage': 'localforage',
          'toastify-js': 'Toastify',
          'blueimp-md5': 'md5',
          'tabulator-tables': 'Tabulator',
          'viewerjs': 'Viewer',
          'qrcodejs': 'QRCode',
          'layui-layer': 'layer',
        },
      },
    }),
  ],
});